# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68d947326aacd4acf68a28a82bb599f2960b2b6e7a469092cf714949fa54b231f05098c880205a65e1bf7d613aa396972c733cc0404fea3943d8c9c460a95a21

test:
  secret_key_base: 90562d6588851b69f922a267114df7c36db0bf9932ca8e2a1313b3913cbd152f643d2bfb9b7b5a48a78b98ee07e578d02f79ae9b3f3eb82cc7caf47840f5ee8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
